name = "silycat---tugasit"

pages_build_output_dir = "."


[build]
command = "npm run build"

[vars]
MY_API_KEY = "c82fb0ea236e48ef332366f8fb96b57376eac"

[env.production]
name = "silycat---tugasit"
entry-point = "index.html"